<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
    ),
  ),
  'readme' => '',
  'key' => 'bi',
  'author' => 'lavaei',
  'description' => 'اطلاعات پایه',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'bi',
  'published_date' => '2023-12-03 11:51:56',
  'type' => 'module',
  'version' => 1701604317,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'bi',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'bi_actionManagement',
      'class' => 'bi_actionManagement',
      'path' => 'modules/bi_actionManagement/bi_actionManagement.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'bi_activityArea',
      'class' => 'bi_activityArea',
      'path' => 'modules/bi_activityArea/bi_activityArea.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'bi_allowedEmergancy',
      'class' => 'bi_allowedEmergancy',
      'path' => 'modules/bi_allowedEmergancy/bi_allowedEmergancy.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'bi_allowedStatus',
      'class' => 'bi_allowedStatus',
      'path' => 'modules/bi_allowedStatus/bi_allowedStatus.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'bi_customersGroup',
      'class' => 'bi_customersGroup',
      'path' => 'modules/bi_customersGroup/bi_customersGroup.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'bi_defaultDescriptions',
      'class' => 'bi_defaultDescriptions',
      'path' => 'modules/bi_defaultDescriptions/bi_defaultDescriptions.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'bi_importType',
      'class' => 'bi_importType',
      'path' => 'modules/bi_importType/bi_importType.php',
      'tab' => true,
    ),
    7 => 
    array (
      'module' => 'bi_introductionMethod',
      'class' => 'bi_introductionMethod',
      'path' => 'modules/bi_introductionMethod/bi_introductionMethod.php',
      'tab' => true,
    ),
    8 => 
    array (
      'module' => 'bi_language',
      'class' => 'bi_language',
      'path' => 'modules/bi_language/bi_language.php',
      'tab' => 1,
    ),
    9 => 
    array (
      'module' => 'bi_locationArea',
      'class' => 'bi_locationArea',
      'path' => 'modules/bi_locationArea/bi_locationArea.php',
      'tab' => true,
    ),
    10 => 
    array (
      'module' => 'bi_metadata',
      'class' => 'bi_metadata',
      'path' => 'modules/bi_metadata/bi_metadata.php',
      'tab' => 1,
    ),
    11 => 
    array (
      'module' => 'bi_organizationChart',
      'class' => 'bi_organizationChart',
      'path' => 'modules/bi_organizationChart/bi_organizationChart.php',
      'tab' => true,
    ),
    12 => 
    array (
      'module' => 'bi_organizationPositions',
      'class' => 'bi_organizationPositions',
      'path' => 'modules/bi_organizationPositions/bi_organizationPositions.php',
      'tab' => true,
    ),
    13 => 
    array (
      'module' => 'bi_requestKinds',
      'class' => 'bi_requestKinds',
      'path' => 'modules/bi_requestKinds/bi_requestKinds.php',
      'tab' => true,
    ),
    14 => 
    array (
      'module' => 'bi_requestKindsGroup',
      'class' => 'bi_requestKindsGroup',
      'path' => 'modules/bi_requestKindsGroup/bi_requestKindsGroup.php',
      'tab' => true,
    ),
    15 => 
    array (
      'module' => 'bi_serviceGroup',
      'class' => 'bi_serviceGroup',
      'path' => 'modules/bi_serviceGroup/bi_serviceGroup.php',
      'tab' => true,
    ),
    16 => 
    array (
      'module' => 'bi_telecommunicationPrefixes',
      'class' => 'bi_telecommunicationPrefixes',
      'path' => 'modules/bi_telecommunicationPrefixes/bi_telecommunicationPrefixes.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_actionmanagement_bi_defaultdescriptions_bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_actionmanagement_users_bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_requestkinds_bi_defaultdescriptions_bi_defaultDescriptions.php',
      'to_module' => 'bi_defaultDescriptions',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_requestkinds_bi_defaultdescriptions_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_requestkinds_bi_allowedstatus_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_requestkinds_bi_allowedemergancy_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/bi_requestkindsgroup_bi_allowedstatus_bi_requestKindsGroup.php',
      'to_module' => 'bi_requestKindsGroup',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_actionmanagement_bi_defaultdescriptionsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_actionmanagement_usersMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_requestkinds_bi_defaultdescriptionsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_requestkinds_bi_allowedstatusMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_requestkinds_bi_allowedemergancyMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/bi_requestkindsgroup_bi_allowedstatusMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_actionManagement',
      'to' => 'modules/bi_actionManagement',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_activityArea',
      'to' => 'modules/bi_activityArea',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_allowedEmergancy',
      'to' => 'modules/bi_allowedEmergancy',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_allowedStatus',
      'to' => 'modules/bi_allowedStatus',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_customersGroup',
      'to' => 'modules/bi_customersGroup',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_defaultDescriptions',
      'to' => 'modules/bi_defaultDescriptions',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_importType',
      'to' => 'modules/bi_importType',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_introductionMethod',
      'to' => 'modules/bi_introductionMethod',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_language',
      'to' => 'modules/bi_language',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_locationArea',
      'to' => 'modules/bi_locationArea',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_metadata',
      'to' => 'modules/bi_metadata',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_organizationChart',
      'to' => 'modules/bi_organizationChart',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_organizationPositions',
      'to' => 'modules/bi_organizationPositions',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_requestKinds',
      'to' => 'modules/bi_requestKinds',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_requestKindsGroup',
      'to' => 'modules/bi_requestKindsGroup',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_serviceGroup',
      'to' => 'modules/bi_serviceGroup',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bi_telecommunicationPrefixes',
      'to' => 'modules/bi_telecommunicationPrefixes',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_defaultDescriptions.php',
      'to_module' => 'bi_defaultDescriptions',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_defaultDescriptions.php',
      'to_module' => 'bi_defaultDescriptions',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_allowedStatus.php',
      'to_module' => 'bi_allowedStatus',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
      'language' => 'en_us',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_allowedEmergancy.php',
      'to_module' => 'bi_allowedEmergancy',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_allowedStatus.php',
      'to_module' => 'bi_allowedStatus',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/bi_requestKindsGroup.php',
      'to_module' => 'bi_requestKindsGroup',
      'language' => 'en_us',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_GB.lang.php',
      'to_module' => 'application',
      'language' => 'en_GB',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/fa_IR.lang.php',
      'to_module' => 'application',
      'language' => 'fa_IR',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_actionmanagement_bi_defaultdescriptions_bi_defaultDescriptions.php',
      'to_module' => 'bi_defaultDescriptions',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_actionmanagement_bi_defaultdescriptions_bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_actionmanagement_users_Users.php',
      'to_module' => 'Users',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_actionmanagement_users_bi_actionManagement.php',
      'to_module' => 'bi_actionManagement',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_defaultdescriptions_bi_defaultDescriptions.php',
      'to_module' => 'bi_defaultDescriptions',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_defaultdescriptions_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_allowedstatus_bi_allowedStatus.php',
      'to_module' => 'bi_allowedStatus',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_allowedstatus_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_allowedemergancy_bi_allowedEmergancy.php',
      'to_module' => 'bi_allowedEmergancy',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkinds_bi_allowedemergancy_bi_requestKinds.php',
      'to_module' => 'bi_requestKinds',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkindsgroup_bi_allowedstatus_bi_allowedStatus.php',
      'to_module' => 'bi_allowedStatus',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/bi_requestkindsgroup_bi_allowedstatus_bi_requestKindsGroup.php',
      'to_module' => 'bi_requestKindsGroup',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'bi_actionmanagement_users_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);